language: php

php:
  - 5.3
  - 5.4
  - 5.5
  
branches:
  only:
    - master
    - develop

before_install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install
  - cd tests

script:
  - phpunit -c phpunit-simple.xml
  
notifications:
  email:
    - kelmadics@gmail.com