language: php

php:
  - 5.3
  - 5.4
  - 5.5
  
branches:
  only:
    - develop

before_install:
  - cd ..
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git
  - cd ZendSkeletonApplication
  - rm composer.json
  - cp ../OAuth2Provider/travis.composer.json ./composer.json
  - php composer.phar install --dev
  - cd vendor/franz-deleon/fdl-oauth2-provider/tests

script:
  - phpunit -c phpunit-travis.xml
  
notifications:
  email:
    - kelmadics@gmail.com