language: php

php:
  - 5.3
  - 5.4
  - 5.5
  
branches:
  only:
    - develop
    - master

before_install:
  - chmod 777 .travis/travis.composer.json
  - export GIT_BRANCH=$(git branch 2>/dev/null| sed -n '/^\*/s/^\* //p')
  - sed -i "s/%branch%/${GIT_BRANCH}/g" .travis/travis.composer.json
  - cat .travis/travis.composer.json
  - cd ..
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git
  - cd ZendSkeletonApplication
  - rm composer.json
  - cp ../OAuth2Provider/.travis/travis.composer.json ./composer.json
  - php composer.phar self-update
  - php composer.phar install --dev
  - cd vendor/franz-deleon/fdl-oauth2-provider/tests

script:
  - phpunit -c phpunit-travis.xml
  
notifications:
  email:
    - kelmadics@gmail.com