language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
branches:
  only:
    - develop
    - master

before_install:
  - chmod 777 .travis/travis.composer.json
  - sed -i "s/%branch%/${TRAVIS_BRANCH}/g" .travis/travis.composer.json
  - cd ..
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git
  - cd ZendSkeletonApplication
  - rm composer.json
  - cp ../OAuth2Provider/.travis/travis.composer.json ./composer.json
  - composer install --dev --prefer-source
  - cd vendor/franz-deleon/fdl-oauth2-provider/tests

script:
  - phpunit -c phpunit-travis.xml
  
notifications:
  email:
    - kelmadics@gmail.com
    
matrix:
  allow_failures:
    - php: hhvm