language: php

php:
  - 5.3
  - 5.4
  - 5.5
  
branches:
  only:
    - develop

before_install:
  - cd ..
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git
  - cd ZendSkeletonApplication
  - php composer.phar self-update
  - php composer.phar require franz-deleon/fdl-oauth2-provider:dev-develop
  - cd vendor/franz-deleon/fdl-oauth2-provider/tests

script:
  - phpunit -c phpunit-travis.xml
  
notifications:
  email:
    - kelmadics@gmail.com